src/main/java/pl/tfal/casino/UserBean.java
/*
 Copyright 2014 Tomasz Fal tomasz.fal@gmail.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */
package pl.tfal.casino;

import java.io.Serializable;
import java.util.logging.Logger;
import javax.enterprise.context.SessionScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.TypedQuery;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import pl.tfal.casino.encje.Uzytkownik;

@ManagedBean(name = "user")
@SessionScoped
public class UserBean implements Serializable
{
    private static final Logger logger = Logger.getLogger("pl.tfal.casino");
    @PersistenceContext(unitName = "casino_pu")
    private EntityManager em;
    private Long id;
    private String name;

    public Uzytkownik getUzytkownik()
    {
        TypedQuery<Uzytkownik> query = em.createNamedQuery("Uzytkowni.findByLogin", Uzytkownik.class);
        query.setParameter("login", getName());
        return query.getSingleResult();
    }

    public Long getId()
    {
        if (id == null)
        {
            id = getUzytkownik().getIdUzytkownicy();
        }
        return id;
    }

    public Long getIdImprezy()
    {
        return 1L;
    }

    public boolean isAdmin()
    {
        ExternalContext context = FacesContext.getCurrentInstance().getExternalContext();
        Object requestObject = context.getRequest();
        if (!(requestObject instanceof HttpServletRequest))
        {
            logger.severe("typ obiektu żądania: " + requestObject.getClass());
            return false;
        }
        HttpServletRequest request = (HttpServletRequest) requestObject;
        return request.isUserInRole("adminuser");
    }

    public String logout()
    {
        ((HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false)).invalidate();
        return "login";
    }

    private String getName()
    {
        if (name == null)
        {
            getUserData();
        }
        return name == null ? "" : name;
    }

    private void getUserData()
    {
        ExternalContext context = FacesContext.getCurrentInstance().getExternalContext();
        Object requestObject = context.getRequest();
        if (!(requestObject instanceof HttpServletRequest))
        {
            logger.severe("typ obiektu żądania: " + requestObject.getClass());
            return;
        }
        HttpServletRequest request = (HttpServletRequest) requestObject;
        name = request.getRemoteUser();
    }
}

src/main/webapp/logi.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p2="http://primefaces.prime.com.tr/ui"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <head><title>IGNORED</title></head>
    <body>
    <ui:composition template="/templates/szablon.xhtml">
        <ui:define name="windowTitle">
            Logi
        </ui:define>

        <ui:define name="content">
            <f:event type="javax.faces.event.PreRenderComponentEvent" listener="#{logiView.init()}" />            
            <h:form id="logiForm" prependId="false">
                <p:dataTable 
                    id="logTable" 
                    lazy="true"
                    value="#{logiView.lazyModel}" 
                    var="d" 
                    editable="false" 
                    style="margin-bottom: 20px"
                    rows="20"
                    paginator="true"
                    paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                    rowsPerPageTemplate="20, 50, 100">
                    <f:facet name="header">
                        Logi
                    </f:facet>

                    <p:column headerText="Data">
                        <h:outputText value="#{d.data}">
                            <f:convertDateTime pattern="dd.MM.yyyy HH:mm:ss" />
                        </h:outputText>
                    </p:column>
                    <p:column headerText="Użytkownik">
                        <h:outputText value="#{not empty d.uzytkownik ? d.uzytkownik.nazwa : ''}" />
                    </p:column>
                    <p:column headerText="Funkcja">
                        <h:outputText value="#{d.funkcja}" />
                    </p:column>
                </p:dataTable>
            </h:form>
        </ui:define>
    </ui:composition>
</body>
</html>

src/main/webapp/login.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <head><title>IGNORED</title></head>
    <h:body>
        <ui:composition template="/templates/szablonLogin.xhtml">
            <ui:define name="windowTitle">
                #{msgs.loginFormTitle}
            </ui:define>

            <ui:define name="content">
                <h:form id="login" onsubmit="document.getElementById('login').action = 'j_security_check';" prependId="false">
                    <p:focus for="j_username" />
                    <p:panelGrid columns="2" style="margin: 100px auto;">
                        <f:facet name="header">
                            <h:outputText style="text-align: center" value="Logowanie" />
                        </f:facet>
                        <h:outputLabel for="j_username" value="#{msgs.loginFormUsername}:" />
                        <p:inputText id="j_username" name='j_username' />
                        <h:outputLabel for="j_password" value="#{msgs.loginFormPassword}:" />
                        <p:password id="j_password" name='j_password' />
                        <p:spacer />
                        <p:commandButton id="submit" value="#{msgs.loginFormLoginButton}" ajax="false" />
                        <f:facet name="footer">
                            <h:outputText style="text-align: center; font-size: xx-small;" value="#{msgs.versionCaption}: #{msgs.versionNumber}" />
                        </f:facet>
                    </p:panelGrid>
                </h:form>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

src/main/webapp/noauth.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <head><title>IGNORED</title></head>
    <h:body>
        <ui:composition template="/templates/szablonLogin.xhtml">
            <ui:define name="windowTitle">
                #{msgs.noAuthFormTitle}
            </ui:define>

            <ui:define name="content">
                <h:form>
                    <p:panelGrid columns="1" style="margin: 100px auto;">
                        <p:column>
                            <h:outputLabel value="#{msgs.noAuthFormHeader}" />
                        </p:column>
                        <p:column>
                            <p:button outcome="login" value="#{msgs.noAuthFormTryAgain}" />
                        </p:column>
                    </p:panelGrid>
                </h:form>
            </ui:define>    
        </ui:composition> 
    </h:body>
</html>

src/main/webapp/ranking.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <head><title>IGNORED</title></head>
    <body>
        <ui:composition template="/templates/szablon.xhtml">
            <ui:define name="windowTitle">
                Ranking
            </ui:define>

            <ui:define name="content">
                <h:form id="form">
                    <p:growl id="msgs" showDetail="true"/>

                    <p:dataTable id="ranking" value="#{rankingView.ranking}" var="d" rowKey="#{d.idUzytkownika}" editable="false" style="margin-bottom:20px">
                        <f:facet name="header">
                            Ranking użytkowników
                        </f:facet>

                        <p:column headerText="ID" rendered="#{user.admin}">
                            <h:outputText value="#{d.idUzytkownika}" />
                        </p:column>
                        <p:column headerText="Pozycja" style="width: 70px; text-align: center">
                            <h:outputText value="#{d.pozycja}" style="font-weight: bold" />
                        </p:column>
                        <p:column headerText="Zmiana" style="width: 70px; text-align: center">
                            <h:outputText value="#{d.zmianaPozycji}" style="font-weight: bold; color: #{d.zmianaPozycji eq 0 ? 'black' : (d.zmianaPozycji lt 0 ? 'red' : 'green')}" />
                        </p:column>
                        <p:column headerText="Użytkownik">
                            <h:outputText value="#{d.nazwaUzytkownika}" />
                        </p:column>
                        <p:column headerText="Suma punktów" style="width: 110px; text-align: center">
                            <h:outputText value="#{d.punktySuma}" />
                        </p:column>
                        <p:column headerText="Strata do poprzedniego" style="width: 110px; text-align: center">
                            <h:outputText value="#{d.punktyStrataDoPoprzedniego}" />
                        </p:column>
                        <p:column headerText="Strata do pierwszego" style="width: 110px; text-align: center">
                            <h:outputText value="#{d.punktyStrataDoPierwszego}" />
                        </p:column>
                        <p:column headerText="Trafienia za 3" style="width: 110px; text-align: center">
                            <h:outputText value="#{d.punktyIlosc3}" />
                        </p:column>
                        <p:column headerText="Trafienia za 1" style="width: 110px; text-align: center">
                            <h:outputText value="#{d.punktyIlosc1}" />
                        </p:column>
                        <p:column headerText="Punkty za mistrza" style="width: 110px; text-align: center">
                            <h:outputText value="#{d.punktyMistrz}" />
                        </p:column>
                        <p:column headerText="#" style="width: 60px; text-align: center">
                            <h:link outcome="rankingHistoryczny">
                                <f:param name="idUzytkownika" value="#{d.idUzytkownika}" />
                                <h:outputText value="Zmiany" />
                            </h:link>
                        </p:column>
                    </p:dataTable>
                </h:form>
            </ui:define>
        </ui:composition>
    </body>
</html>

src/main/webapp/rankingHistoryczny.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p2="http://primefaces.prime.com.tr/ui"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <head><title>IGNORED</title></head>
    <body>
    <ui:composition template="/templates/szablon.xhtml">
        <ui:define name="windowTitle">
            Zmiany w rankingu
        </ui:define>

        <ui:define name="content">
            <h:form id="form">
                <p:growl id="msgs" showDetail="true"/>

                <p:dataTable id="ranking" value="#{rankingHistorycznyView.rankingHistoryczny}" var="d" editable="false" style="margin-bottom:20px">
                    <f:facet name="header">
                        Zmiany w rankingu użytkownika #{rankingHistorycznyView.uzytkownik.nazwa}
                    </f:facet>

                    <p:column headerText="Data">
                        <h:outputText value="#{d.osXOpis}" />
                    </p:column>
                    <p:column headerText="Pozycja">
                        <h:outputText value="#{d.pozycja}" />
                    </p:column>
                    <p:column headerText="Suma punktów">
                        <h:outputText value="#{d.punktySuma}" />
                    </p:column>
                </p:dataTable>
                <p><h:link outcome="ranking" value="Powrót do rankingu" /></p>
            </h:form>
        </ui:define>
    </ui:composition>
</body>
</html>

src/main/webapp/szczegolySpotkania.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <head><title>IGNORED</title></head>
    <body>
        <ui:composition template="/templates/szablon.xhtml">
            <ui:define name="windowTitle">
                Szczegóły spotkania
            </ui:define>

            <ui:define name="content">
                <h:form id="form">
                    <p:dataTable id="szczegoly" value="#{szczegolySpotkaniaView.szczegoly}" var="d" editable="false" style="margin-bottom:20px">
                        <f:facet name="header">
                            <table cellpadding="2">
                                <tr>
                                    <td align="right">#{szczegolySpotkaniaView.spotkanie.druzyna1.nazwa}</td>
                                    <td align="left">#{szczegolySpotkaniaView.spotkanie.druzyna2.nazwa}</td>
                                </tr>
                                <tr>
                                    <td align="right">#{szczegolySpotkaniaView.spotkanie.wynik1}</td>
                                    <td align="left">#{szczegolySpotkaniaView.spotkanie.wynik2}</td>
                                </tr>
                            </table>
                        </f:facet>

                        <p:column headerText="Użytkownik">
                            <h:outputText value="#{d.nazwaUzytkownika}" />
                        </p:column>
                        <p:column headerText="Typ" style="width: 110px; text-align: center;" rendered="#{not user.admin}">
                            <h:outputText value="#{d.typDruzyny1} : #{d.typDruzyny2}" />
                        </p:column>
                        <p:column headerText="Punkty" style="width: 70px; text-align: center;" rendered="#{not user.admin}">
                            <h:outputText value="#{d.punkty}" />
                        </p:column>
                    </p:dataTable>
                    <h:link outcome="wyniki" value="Powrót do wyników" />
                </h:form>
            </ui:define>
        </ui:composition>
    </body>
</html>

src/main/webapp/templates/szablon.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <h:outputStylesheet library="css" name="default.css"/>
        <h:outputStylesheet library="css" name="cssLayout.css"/>
        <title><ui:insert name="windowTitle"/></title>
        <link rel="shortcut icon" href="" />
    </h:head>

    <h:body>
        <div id="top">
            <h:form>
                <p:menubar>
                    <p:menuitem value="Typowanie wyników" outcome="typy" rendered="#{not user.admin}" icon="ui-icon-check" />
                    <p:menuitem value="Wyniki spotkań" outcome="wyniki" icon="ui-icon-calculator" />
                    <p:menuitem value="Ranking użytkowników" outcome="ranking" rendered="#{not user.admin}" icon="ui-icon-person" />
                    <p:menuitem value="Typowanie mistrza" outcome="typMistrza" rendered="#{not user.admin}" icon="ui-icon-check" />
                    <p:menuitem value="Logi" outcome="logi" rendered="#{user.admin}" icon="ui-icon-gear" />
                    <p:menuitem value="Zmiana hasła" outcome="zmianaHasla" icon="ui-icon-key" />
                    <f:facet name="options">
                        <p:commandButton value="Wyloguj" icon="ui-icon-extlink" action="#{user.logout()}" ajax="false" />
                    </f:facet>
                </p:menubar>
            </h:form>
        </div>

        <div id="content" class="center_content">
            <ui:insert name="content">Content</ui:insert>
        </div>

        <div id="bottom">
            <h:outputText style="text-align: center; font-size: xx-small;" value="#{msgs.versionCaption}: #{msgs.versionNumber}" />
        </div>
    </h:body>
</html>

src/main/webapp/templates/szablonLogin.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <h:outputStylesheet library="css" name="default.css"/>
        <h:outputStylesheet library="css" name="cssLayout.css"/>
        <title><ui:insert name="windowTitle"/></title>
        <link rel="shortcut icon" href="" />
    </h:head>

    <h:body>
        <div id="content" class="center_content">
            <ui:insert name="content">Content</ui:insert>
        </div>
    </h:body>

</html>

src/main/webapp/typMistrza.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <head><title>IGNORED</title></head>
    <body>
        <ui:composition template="/templates/szablon.xhtml">
            <ui:define name="windowTitle">
                Typowanie mistrza
            </ui:define>

            <ui:define name="content">
                <h:form id="form">
                    <ui:remove>
                        <p:panel>
                            Mistrz:
                            <p:selectOneMenu id="druzyny" value="#{typMistrzaView.idDruzynyMistrz}">
                                <c:forEach items="#{typMistrzaView.druzyny}" var="d" varStatus="loop">
                                    <f:selectItem itemValue="#{d.idDruzyny}" itemLabel="#{d.nazwa}" />
                                </c:forEach>
                            </p:selectOneMenu>
                            <p:commandButton id="submitButton" actionListener="#{typMistrzaView.zmienTyp}" value="Zmień" ajax="false"/>
                        </p:panel>
                        <p:messages id="messages" showDetail="false" autoUpdate="true" closable="true" />
                        <br />
                    </ui:remove>
                    <p:dataTable id="ranking" value="#{typMistrzaView.typy}" var="d" editable="false" style="margin-bottom:20px">
                        <f:facet name="header">
                            Typy użytkowników
                        </f:facet>

                        <p:column headerText="Użytkownik">
                            <h:outputText value="#{d.nazwaUzytkownika}" />
                        </p:column>
                        <p:column headerText="Typ na mistrza">
                            <h:graphicImage library="imgs" name="flags/#{d.flagaDruzyny}" rendered="#{not empty d.flagaDruzyny}" style="vertical-align: middle;" /><h:outputText value="&#160;" /><h:outputText value="#{d.nazwaDruzyny}" />
                        </p:column>
                    </p:dataTable>
                </h:form>
            </ui:define>
        </ui:composition>
    </body>
</html>

src/main/webapp/wyniki.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <head><title>IGNORED</title>
    </head>
    <body>
        <ui:composition template="/templates/szablon.xhtml">
            <ui:define name="windowTitle">
                Wyniki spotkań
            </ui:define>
            <ui:define name="content">
                <h:form id="form">
                    <p:growl id="msgs" showDetail="false"/>

                    <p:dataTable id="wyniki"
                                 value="#{wynikiView.wyniki}"
                                 var="d"
                                 rowKey="#{d.idSpotkania}"
                                 editable="true"
                                 style="margin-bottom:20px"
                                 rows="20"
                                 paginator="true"
                                 paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                                 rowsPerPageTemplate="20,50,100">
                        <f:facet name="header">
                            Wyniki spotkań
                        </f:facet>

                        <p:ajax event="rowEdit" update=":form:msgs @this" listener="#{wynikiView.onRowUpdate}" />
                        <p:ajax event="rowEditCancel" update=":form:msgs @this" listener="#{wynikiView.onRowCancel}" />

                        <p:column headerText="ID" rendered="#{user.admin}">
                            <h:outputText value="#{d.idSpotkania}" />
                        </p:column>
                        <p:column headerText="Nr spotkania">
                            <h:outputText value="#{d.numerSpotkania}" />
                        </p:column>
                        <p:column headerText="Grupa / Faza">
                            <h:outputText value="#{d.nazwaFazy}" />
                        </p:column>
                        <p:column headerText="Data spotkania">
                            <h:outputText value="#{d.dataSpotkania}">
                                <f:convertDateTime pattern="dd.MM HH:mm" />
                            </h:outputText>
                        </p:column>
                        <p:column headerText="Drużyna 1">
                            <h:graphicImage library="imgs" name="flags/#{d.flagaDruzyny1}" rendered="#{not empty d.flagaDruzyny1}" style="vertical-align: middle;" /><h:outputText value="&#160;" /><h:outputText value="#{d.nazwaDruzyny1}" />
                        </p:column>
                        <p:column headerText="Drużyna 2">
                            <h:graphicImage library="imgs" name="flags/#{d.flagaDruzyny2}" rendered="#{not empty d.flagaDruzyny2}" style="vertical-align: middle;" /><h:outputText value="&#160;" /><h:outputText value="#{d.nazwaDruzyny2}" />
                        </p:column>
                        <p:column headerText="Wynik" style="width: 110px; text-align: center;">
                            <p:cellEditor>
                                <f:facet name="output">
                                    <h:outputText value="#{d.wynikDruzyny1} : #{d.wynikDruzyny2}" />
                                </f:facet>
                                <f:facet name="input">
                                    <h:inputText value="#{d.wynikDruzyny1}" size="3" />
                                    <h:inputText value="#{d.wynikDruzyny2}" size="3" />
                                </f:facet>
                            </p:cellEditor>
                        </p:column>
                        <p:column headerText="Typ" style="width: 110px; text-align: center;" rendered="#{not user.admin}">
                            <h:outputText value="#{d.typDruzyny1} : #{d.typDruzyny2}" />
                        </p:column>
                        <p:column headerText="Punkty" style="width: 70px; text-align: center;" rendered="#{not user.admin}">
                            <h:outputText value="#{d.punkty}" />
                        </p:column>
                        <p:column headerText="#" rendered="#{not d.moznaEdytowac and not user.admin}" style="width: 110px; text-align: center;">
                            <h:link outcome="szczegolySpotkania">
                                <f:param name="idSpotkania" value="#{d.idSpotkania}" />
                                <h:outputText value="Szczegóły" />
                            </h:link>
                        </p:column>
                        <p:column headerText="Edycja" style="width: 60px" rendered="#{user.admin}">
                            <p:rowEditor />
                        </p:column>
                    </p:dataTable>
                    <p:commandButton id="submitButton" actionListener="#{wynikiView.przeliczPunkty}" value="Przelicz punkty" rendered="#{user.admin}" ajax="false"/>
                    <p:messages id="messages" showDetail="false" autoUpdate="true" closable="true" />
                </h:form>
            </ui:define>
        </ui:composition>
    </body>
</html>

src/main/webapp/zmianaHasla.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <head><title>IGNORED</title></head>
    <body>
        <ui:composition template="/templates/szablon.xhtml">
            <ui:define name="windowTitle">
                Zmiana hasła
            </ui:define>

            <ui:define name="content">
                <h:form id="form">
                    <table>
                        <tr>
                            <td>Bieżące hasło:</td>
                            <td><p:password  value="#{zmianaHaslaView.stareHaslo}" /></td>
                        </tr>
                        <tr>
                            <td>Nowe hasło:</td>
                            <td><p:password value="#{zmianaHaslaView.noweHaslo}" /></td>
                        </tr>
                        <tr>
                            <td>Potwierdź nowe hasło:</td>
                            <td><p:password value="#{zmianaHaslaView.noweHaslo2}" /></td>
                        </tr>
                    </table>
                    <p:commandButton id="submitButton" actionListener="#{zmianaHaslaView.zmienHaslo}" value="Zmień" ajax="false"/>
                    <p:messages id="messages" showDetail="true" autoUpdate="true" closable="true" />
                </h:form>
            </ui:define>
        </ui:composition>
    </body>
</html>